### ISSUE TITLE
help with understanding how the coordinates are updated

### ISSUE THREAD

**Issue by tarak77** [lh3/hickit#26]
Hi @lh3 ,
I am having a little trouble understanding how the coordinates in hickit code are updated? 
I know that in nuclear_dynamics, the change in position is velocitytime + 0.5acceleration*time^2. The calculation of the acceleration is force/mass with an extra term.

Is hickit using similar equation? Also, while going over the code I did not understand the const max_f and coef_moment?

Any help will be great!

**Comment by tanlongzhi** [comment]
Hi @tarak77,

As far as I understand (@lh3 please correct me if I got it wrong), hickit does *not* model Newtonian dynamics (e.g. 2nd order differential equation) as in nuc_dynamics. Instead, hickit uses a simplified, 1st order equation that does *not* have velocity, but rather a "force/velocity hybrid". Please see the code [fdg.c](https://github.com/lh3/hickit/blob/master/fdg.c) for details.

In particular, in the main function `hk_fdg1()`, the "force" matrix `f[][]` stores the repulsive and attractive forces via `update_force()` as in nuc_dynamics. However, this "force" is then used more like a "velocity" to update particle coordinates:

Hickit first calculates the root-mean-square (RMS) "force" `t` from `f[][]` with `fv3_L2()` and `sqrtf()`. This is analogous to RMS velocity for temperature calculation in nuc_dynamics. The RMS value is displayed as `RMS_force` in standard error, and will be normalized down to `max_f` (together with the entire `f[][]`) if it exceeds `max_f`.

Hickit then updates particle coordinates `x[][]` using `f[][]` as a "velocity", by incrementing `x[i][j]` with `f[i][j] * step`. I don't think `coef_moment` is ever used, because the way `hk_fdg1()` is used, `x0[][]` and `x[][]` are always the same (again, @lh3 please correct me if I got it wrong).

Best,
Tan

**Comment by lh3** [comment]
hickit poses this as an optimization problem. Force is proportional to gradient. We can use gradient descent to find the optima. In the code, hickit is using gradient descent with a momentum term as is often used in deep learning.

Different formulations lead to largely the same result. They differ in convergence time and in the robustness to local optima.

**Comment by tanlongzhi** [comment]
Thanks a lot @lh3 for the explanation! Under a gradient descent framework, everything makes much more sense now.

@tarak77, we built the whole [fdg.c](https://github.com/lh3/hickit/blob/master/fdg.c) (short for "force-directed graph") to see how much we can simplify nuc_dynamics's energy minimization (i.e. optimization) procedure.

From hickit's results, the use of momentum (i.e. 2nd order Newtonian dynamics) or of random/thermal fluctuations turns out not essential; however, hierarchical optimization from coarse to fine bin sizes turns out useful.

Best,
Tan

**Comment by tarak77** [comment]
I understand now. Thank you!
